//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUI.ServiceStock {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCompra", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DetalleCompra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdproveedorField;
        
        private int IdDetalleCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdProductoField;
        
        private int IdStockField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCompra {
            get {
                return this.IdCompraField;
            }
            set {
                if ((this.IdCompraField.Equals(value) != true)) {
                    this.IdCompraField = value;
                    this.RaisePropertyChanged("IdCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Idproveedor {
            get {
                return this.IdproveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdproveedorField, value) != true)) {
                    this.IdproveedorField = value;
                    this.RaisePropertyChanged("Idproveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdDetalleCompra {
            get {
                return this.IdDetalleCompraField;
            }
            set {
                if ((this.IdDetalleCompraField.Equals(value) != true)) {
                    this.IdDetalleCompraField = value;
                    this.RaisePropertyChanged("IdDetalleCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdProductoField, value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int IdStock {
            get {
                return this.IdStockField;
            }
            set {
                if ((this.IdStockField.Equals(value) != true)) {
                    this.IdStockField = value;
                    this.RaisePropertyChanged("IdStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Stock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdStockField;
        
        private int IdDetalleCompraField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdStock {
            get {
                return this.IdStockField;
            }
            set {
                if ((this.IdStockField.Equals(value) != true)) {
                    this.IdStockField = value;
                    this.RaisePropertyChanged("IdStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdDetalleCompra {
            get {
                return this.IdDetalleCompraField;
            }
            set {
                if ((this.IdDetalleCompraField.Equals(value) != true)) {
                    this.IdDetalleCompraField = value;
                    this.RaisePropertyChanged("IdDetalleCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceStock.WebServiceStockSoap")]
    public interface WebServiceStockSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento detalle del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarCompra", ReplyAction="*")]
        CapaUI.ServiceStock.ServicioinsertarCompraResponse ServicioinsertarCompra(CapaUI.ServiceStock.ServicioinsertarCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarCompraResponse> ServicioinsertarCompraAsync(CapaUI.ServiceStock.ServicioinsertarCompraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento detalle del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarCompraDetalle", ReplyAction="*")]
        CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponse ServicioinsertarCompraDetalle(CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarCompraDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponse> ServicioinsertarCompraDetalleAsync(CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento detalle del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarStock", ReplyAction="*")]
        CapaUI.ServiceStock.ServicioinsertarStockResponse ServicioinsertarStock(CapaUI.ServiceStock.ServicioinsertarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarStockResponse> ServicioinsertarStockAsync(CapaUI.ServiceStock.ServicioinsertarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioBuscaLastCompra", ReplyAction="*")]
        int ServicioBuscaLastCompra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioBuscaLastCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServicioBuscaLastCompraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioBuscaLastDetalleCompra", ReplyAction="*")]
        int ServicioBuscaLastDetalleCompra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioBuscaLastDetalleCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServicioBuscaLastDetalleCompraAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idDetalle del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioObtenerStockPorIdDetalle", ReplyAction="*")]
        CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponse ServicioObtenerStockPorIdDetalle(CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioObtenerStockPorIdDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponse> ServicioObtenerStockPorIdDetalleAsync(CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento stock del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioActualizarStock", ReplyAction="*")]
        CapaUI.ServiceStock.ServicioActualizarStockResponse ServicioActualizarStock(CapaUI.ServiceStock.ServicioActualizarStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioActualizarStock", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioActualizarStockResponse> ServicioActualizarStockAsync(CapaUI.ServiceStock.ServicioActualizarStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarCompra", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioinsertarCompraRequestBody Body;
        
        public ServicioinsertarCompraRequest() {
        }
        
        public ServicioinsertarCompraRequest(CapaUI.ServiceStock.ServicioinsertarCompraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarCompraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceStock.DetalleCompra detalle;
        
        public ServicioinsertarCompraRequestBody() {
        }
        
        public ServicioinsertarCompraRequestBody(CapaUI.ServiceStock.DetalleCompra detalle) {
            this.detalle = detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarCompraResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioinsertarCompraResponseBody Body;
        
        public ServicioinsertarCompraResponse() {
        }
        
        public ServicioinsertarCompraResponse(CapaUI.ServiceStock.ServicioinsertarCompraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarCompraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioinsertarCompraResult;
        
        public ServicioinsertarCompraResponseBody() {
        }
        
        public ServicioinsertarCompraResponseBody(bool ServicioinsertarCompraResult) {
            this.ServicioinsertarCompraResult = ServicioinsertarCompraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarCompraDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarCompraDetalle", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequestBody Body;
        
        public ServicioinsertarCompraDetalleRequest() {
        }
        
        public ServicioinsertarCompraDetalleRequest(CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarCompraDetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceStock.DetalleCompra detalle;
        
        public ServicioinsertarCompraDetalleRequestBody() {
        }
        
        public ServicioinsertarCompraDetalleRequestBody(CapaUI.ServiceStock.DetalleCompra detalle) {
            this.detalle = detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarCompraDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarCompraDetalleResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponseBody Body;
        
        public ServicioinsertarCompraDetalleResponse() {
        }
        
        public ServicioinsertarCompraDetalleResponse(CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarCompraDetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioinsertarCompraDetalleResult;
        
        public ServicioinsertarCompraDetalleResponseBody() {
        }
        
        public ServicioinsertarCompraDetalleResponseBody(bool ServicioinsertarCompraDetalleResult) {
            this.ServicioinsertarCompraDetalleResult = ServicioinsertarCompraDetalleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarStock", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioinsertarStockRequestBody Body;
        
        public ServicioinsertarStockRequest() {
        }
        
        public ServicioinsertarStockRequest(CapaUI.ServiceStock.ServicioinsertarStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceStock.DetalleCompra detalle;
        
        public ServicioinsertarStockRequestBody() {
        }
        
        public ServicioinsertarStockRequestBody(CapaUI.ServiceStock.DetalleCompra detalle) {
            this.detalle = detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioinsertarStockResponseBody Body;
        
        public ServicioinsertarStockResponse() {
        }
        
        public ServicioinsertarStockResponse(CapaUI.ServiceStock.ServicioinsertarStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioinsertarStockResult;
        
        public ServicioinsertarStockResponseBody() {
        }
        
        public ServicioinsertarStockResponseBody(bool ServicioinsertarStockResult) {
            this.ServicioinsertarStockResult = ServicioinsertarStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioObtenerStockPorIdDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioObtenerStockPorIdDetalle", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequestBody Body;
        
        public ServicioObtenerStockPorIdDetalleRequest() {
        }
        
        public ServicioObtenerStockPorIdDetalleRequest(CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioObtenerStockPorIdDetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idDetalle;
        
        public ServicioObtenerStockPorIdDetalleRequestBody() {
        }
        
        public ServicioObtenerStockPorIdDetalleRequestBody(string idDetalle) {
            this.idDetalle = idDetalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioObtenerStockPorIdDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioObtenerStockPorIdDetalleResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponseBody Body;
        
        public ServicioObtenerStockPorIdDetalleResponse() {
        }
        
        public ServicioObtenerStockPorIdDetalleResponse(CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioObtenerStockPorIdDetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceStock.Stock ServicioObtenerStockPorIdDetalleResult;
        
        public ServicioObtenerStockPorIdDetalleResponseBody() {
        }
        
        public ServicioObtenerStockPorIdDetalleResponseBody(CapaUI.ServiceStock.Stock ServicioObtenerStockPorIdDetalleResult) {
            this.ServicioObtenerStockPorIdDetalleResult = ServicioObtenerStockPorIdDetalleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioActualizarStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioActualizarStock", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioActualizarStockRequestBody Body;
        
        public ServicioActualizarStockRequest() {
        }
        
        public ServicioActualizarStockRequest(CapaUI.ServiceStock.ServicioActualizarStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioActualizarStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceStock.Stock stock;
        
        public ServicioActualizarStockRequestBody() {
        }
        
        public ServicioActualizarStockRequestBody(CapaUI.ServiceStock.Stock stock) {
            this.stock = stock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioActualizarStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioActualizarStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceStock.ServicioActualizarStockResponseBody Body;
        
        public ServicioActualizarStockResponse() {
        }
        
        public ServicioActualizarStockResponse(CapaUI.ServiceStock.ServicioActualizarStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServicioActualizarStockResponseBody {
        
        public ServicioActualizarStockResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceStockSoapChannel : CapaUI.ServiceStock.WebServiceStockSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceStockSoapClient : System.ServiceModel.ClientBase<CapaUI.ServiceStock.WebServiceStockSoap>, CapaUI.ServiceStock.WebServiceStockSoap {
        
        public WebServiceStockSoapClient() {
        }
        
        public WebServiceStockSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceStockSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceStockSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceStockSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceStock.ServicioinsertarCompraResponse CapaUI.ServiceStock.WebServiceStockSoap.ServicioinsertarCompra(CapaUI.ServiceStock.ServicioinsertarCompraRequest request) {
            return base.Channel.ServicioinsertarCompra(request);
        }
        
        public bool ServicioinsertarCompra(CapaUI.ServiceStock.DetalleCompra detalle) {
            CapaUI.ServiceStock.ServicioinsertarCompraRequest inValue = new CapaUI.ServiceStock.ServicioinsertarCompraRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioinsertarCompraRequestBody();
            inValue.Body.detalle = detalle;
            CapaUI.ServiceStock.ServicioinsertarCompraResponse retVal = ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioinsertarCompra(inValue);
            return retVal.Body.ServicioinsertarCompraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarCompraResponse> CapaUI.ServiceStock.WebServiceStockSoap.ServicioinsertarCompraAsync(CapaUI.ServiceStock.ServicioinsertarCompraRequest request) {
            return base.Channel.ServicioinsertarCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarCompraResponse> ServicioinsertarCompraAsync(CapaUI.ServiceStock.DetalleCompra detalle) {
            CapaUI.ServiceStock.ServicioinsertarCompraRequest inValue = new CapaUI.ServiceStock.ServicioinsertarCompraRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioinsertarCompraRequestBody();
            inValue.Body.detalle = detalle;
            return ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioinsertarCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponse CapaUI.ServiceStock.WebServiceStockSoap.ServicioinsertarCompraDetalle(CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest request) {
            return base.Channel.ServicioinsertarCompraDetalle(request);
        }
        
        public bool ServicioinsertarCompraDetalle(CapaUI.ServiceStock.DetalleCompra detalle) {
            CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest inValue = new CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequestBody();
            inValue.Body.detalle = detalle;
            CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponse retVal = ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioinsertarCompraDetalle(inValue);
            return retVal.Body.ServicioinsertarCompraDetalleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponse> CapaUI.ServiceStock.WebServiceStockSoap.ServicioinsertarCompraDetalleAsync(CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest request) {
            return base.Channel.ServicioinsertarCompraDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarCompraDetalleResponse> ServicioinsertarCompraDetalleAsync(CapaUI.ServiceStock.DetalleCompra detalle) {
            CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest inValue = new CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioinsertarCompraDetalleRequestBody();
            inValue.Body.detalle = detalle;
            return ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioinsertarCompraDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceStock.ServicioinsertarStockResponse CapaUI.ServiceStock.WebServiceStockSoap.ServicioinsertarStock(CapaUI.ServiceStock.ServicioinsertarStockRequest request) {
            return base.Channel.ServicioinsertarStock(request);
        }
        
        public bool ServicioinsertarStock(CapaUI.ServiceStock.DetalleCompra detalle) {
            CapaUI.ServiceStock.ServicioinsertarStockRequest inValue = new CapaUI.ServiceStock.ServicioinsertarStockRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioinsertarStockRequestBody();
            inValue.Body.detalle = detalle;
            CapaUI.ServiceStock.ServicioinsertarStockResponse retVal = ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioinsertarStock(inValue);
            return retVal.Body.ServicioinsertarStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarStockResponse> CapaUI.ServiceStock.WebServiceStockSoap.ServicioinsertarStockAsync(CapaUI.ServiceStock.ServicioinsertarStockRequest request) {
            return base.Channel.ServicioinsertarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioinsertarStockResponse> ServicioinsertarStockAsync(CapaUI.ServiceStock.DetalleCompra detalle) {
            CapaUI.ServiceStock.ServicioinsertarStockRequest inValue = new CapaUI.ServiceStock.ServicioinsertarStockRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioinsertarStockRequestBody();
            inValue.Body.detalle = detalle;
            return ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioinsertarStockAsync(inValue);
        }
        
        public int ServicioBuscaLastCompra() {
            return base.Channel.ServicioBuscaLastCompra();
        }
        
        public System.Threading.Tasks.Task<int> ServicioBuscaLastCompraAsync() {
            return base.Channel.ServicioBuscaLastCompraAsync();
        }
        
        public int ServicioBuscaLastDetalleCompra() {
            return base.Channel.ServicioBuscaLastDetalleCompra();
        }
        
        public System.Threading.Tasks.Task<int> ServicioBuscaLastDetalleCompraAsync() {
            return base.Channel.ServicioBuscaLastDetalleCompraAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponse CapaUI.ServiceStock.WebServiceStockSoap.ServicioObtenerStockPorIdDetalle(CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest request) {
            return base.Channel.ServicioObtenerStockPorIdDetalle(request);
        }
        
        public CapaUI.ServiceStock.Stock ServicioObtenerStockPorIdDetalle(string idDetalle) {
            CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest inValue = new CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequestBody();
            inValue.Body.idDetalle = idDetalle;
            CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponse retVal = ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioObtenerStockPorIdDetalle(inValue);
            return retVal.Body.ServicioObtenerStockPorIdDetalleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponse> CapaUI.ServiceStock.WebServiceStockSoap.ServicioObtenerStockPorIdDetalleAsync(CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest request) {
            return base.Channel.ServicioObtenerStockPorIdDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleResponse> ServicioObtenerStockPorIdDetalleAsync(string idDetalle) {
            CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest inValue = new CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioObtenerStockPorIdDetalleRequestBody();
            inValue.Body.idDetalle = idDetalle;
            return ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioObtenerStockPorIdDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceStock.ServicioActualizarStockResponse CapaUI.ServiceStock.WebServiceStockSoap.ServicioActualizarStock(CapaUI.ServiceStock.ServicioActualizarStockRequest request) {
            return base.Channel.ServicioActualizarStock(request);
        }
        
        public void ServicioActualizarStock(CapaUI.ServiceStock.Stock stock) {
            CapaUI.ServiceStock.ServicioActualizarStockRequest inValue = new CapaUI.ServiceStock.ServicioActualizarStockRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioActualizarStockRequestBody();
            inValue.Body.stock = stock;
            CapaUI.ServiceStock.ServicioActualizarStockResponse retVal = ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioActualizarStock(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioActualizarStockResponse> CapaUI.ServiceStock.WebServiceStockSoap.ServicioActualizarStockAsync(CapaUI.ServiceStock.ServicioActualizarStockRequest request) {
            return base.Channel.ServicioActualizarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceStock.ServicioActualizarStockResponse> ServicioActualizarStockAsync(CapaUI.ServiceStock.Stock stock) {
            CapaUI.ServiceStock.ServicioActualizarStockRequest inValue = new CapaUI.ServiceStock.ServicioActualizarStockRequest();
            inValue.Body = new CapaUI.ServiceStock.ServicioActualizarStockRequestBody();
            inValue.Body.stock = stock;
            return ((CapaUI.ServiceStock.WebServiceStockSoap)(this)).ServicioActualizarStockAsync(inValue);
        }
    }
}
