//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUI.ServiceProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdproductoField;
        
        private int Precio_unitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdproveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaracteristicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Idproducto {
            get {
                return this.IdproductoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdproductoField, value) != true)) {
                    this.IdproductoField = value;
                    this.RaisePropertyChanged("Idproducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Precio_unitario {
            get {
                return this.Precio_unitarioField;
            }
            set {
                if ((this.Precio_unitarioField.Equals(value) != true)) {
                    this.Precio_unitarioField = value;
                    this.RaisePropertyChanged("Precio_unitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Idproveedor {
            get {
                return this.IdproveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdproveedorField, value) != true)) {
                    this.IdproveedorField = value;
                    this.RaisePropertyChanged("Idproveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tipo_producto {
            get {
                return this.Tipo_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_productoField, value) != true)) {
                    this.Tipo_productoField = value;
                    this.RaisePropertyChanged("Tipo_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Caracteristica {
            get {
                return this.CaracteristicaField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristicaField, value) != true)) {
                    this.CaracteristicaField = value;
                    this.RaisePropertyChanged("Caracteristica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.WebServiceProductoSoap")]
    public interface WebServiceProductoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Serviceinsertarproducto", ReplyAction="*")]
        CapaUI.ServiceProducto.ServiceinsertarproductoResponse Serviceinsertarproducto(CapaUI.ServiceProducto.ServiceinsertarproductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Serviceinsertarproducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServiceinsertarproductoResponse> ServiceinsertarproductoAsync(CapaUI.ServiceProducto.ServiceinsertarproductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicebuscaProd", ReplyAction="*")]
        CapaUI.ServiceProducto.ServicebuscaProdResponse ServicebuscaProd(CapaUI.ServiceProducto.ServicebuscaProdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicebuscaProd", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServicebuscaProdResponse> ServicebuscaProdAsync(CapaUI.ServiceProducto.ServicebuscaProdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        CapaUI.ServiceProducto.ServiceActualizaProductoResponse ServiceActualizaProducto(CapaUI.ServiceProducto.ServiceActualizaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServiceActualizaProductoResponse> ServiceActualizaProductoAsync(CapaUI.ServiceProducto.ServiceActualizaProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceinsertarproductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Serviceinsertarproducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProducto.ServiceinsertarproductoRequestBody Body;
        
        public ServiceinsertarproductoRequest() {
        }
        
        public ServiceinsertarproductoRequest(CapaUI.ServiceProducto.ServiceinsertarproductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceinsertarproductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceProducto.Producto producto;
        
        public ServiceinsertarproductoRequestBody() {
        }
        
        public ServiceinsertarproductoRequestBody(CapaUI.ServiceProducto.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceinsertarproductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceinsertarproductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProducto.ServiceinsertarproductoResponseBody Body;
        
        public ServiceinsertarproductoResponse() {
        }
        
        public ServiceinsertarproductoResponse(CapaUI.ServiceProducto.ServiceinsertarproductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceinsertarproductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServiceinsertarproductoResult;
        
        public ServiceinsertarproductoResponseBody() {
        }
        
        public ServiceinsertarproductoResponseBody(bool ServiceinsertarproductoResult) {
            this.ServiceinsertarproductoResult = ServiceinsertarproductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicebuscaProdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicebuscaProd", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProducto.ServicebuscaProdRequestBody Body;
        
        public ServicebuscaProdRequest() {
        }
        
        public ServicebuscaProdRequest(CapaUI.ServiceProducto.ServicebuscaProdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicebuscaProdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string producto;
        
        public ServicebuscaProdRequestBody() {
        }
        
        public ServicebuscaProdRequestBody(string producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicebuscaProdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicebuscaProdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProducto.ServicebuscaProdResponseBody Body;
        
        public ServicebuscaProdResponse() {
        }
        
        public ServicebuscaProdResponse(CapaUI.ServiceProducto.ServicebuscaProdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicebuscaProdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceProducto.Producto ServicebuscaProdResult;
        
        public ServicebuscaProdResponseBody() {
        }
        
        public ServicebuscaProdResponseBody(CapaUI.ServiceProducto.Producto ServicebuscaProdResult) {
            this.ServicebuscaProdResult = ServicebuscaProdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceActualizaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceActualizaProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProducto.ServiceActualizaProductoRequestBody Body;
        
        public ServiceActualizaProductoRequest() {
        }
        
        public ServiceActualizaProductoRequest(CapaUI.ServiceProducto.ServiceActualizaProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceActualizaProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceProducto.Producto producto;
        
        public ServiceActualizaProductoRequestBody() {
        }
        
        public ServiceActualizaProductoRequestBody(CapaUI.ServiceProducto.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceActualizaProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceActualizaProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceProducto.ServiceActualizaProductoResponseBody Body;
        
        public ServiceActualizaProductoResponse() {
        }
        
        public ServiceActualizaProductoResponse(CapaUI.ServiceProducto.ServiceActualizaProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServiceActualizaProductoResponseBody {
        
        public ServiceActualizaProductoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProductoSoapChannel : CapaUI.ServiceProducto.WebServiceProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProductoSoapClient : System.ServiceModel.ClientBase<CapaUI.ServiceProducto.WebServiceProductoSoap>, CapaUI.ServiceProducto.WebServiceProductoSoap {
        
        public WebServiceProductoSoapClient() {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProducto.ServiceinsertarproductoResponse CapaUI.ServiceProducto.WebServiceProductoSoap.Serviceinsertarproducto(CapaUI.ServiceProducto.ServiceinsertarproductoRequest request) {
            return base.Channel.Serviceinsertarproducto(request);
        }
        
        public bool Serviceinsertarproducto(CapaUI.ServiceProducto.Producto producto) {
            CapaUI.ServiceProducto.ServiceinsertarproductoRequest inValue = new CapaUI.ServiceProducto.ServiceinsertarproductoRequest();
            inValue.Body = new CapaUI.ServiceProducto.ServiceinsertarproductoRequestBody();
            inValue.Body.producto = producto;
            CapaUI.ServiceProducto.ServiceinsertarproductoResponse retVal = ((CapaUI.ServiceProducto.WebServiceProductoSoap)(this)).Serviceinsertarproducto(inValue);
            return retVal.Body.ServiceinsertarproductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServiceinsertarproductoResponse> CapaUI.ServiceProducto.WebServiceProductoSoap.ServiceinsertarproductoAsync(CapaUI.ServiceProducto.ServiceinsertarproductoRequest request) {
            return base.Channel.ServiceinsertarproductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServiceinsertarproductoResponse> ServiceinsertarproductoAsync(CapaUI.ServiceProducto.Producto producto) {
            CapaUI.ServiceProducto.ServiceinsertarproductoRequest inValue = new CapaUI.ServiceProducto.ServiceinsertarproductoRequest();
            inValue.Body = new CapaUI.ServiceProducto.ServiceinsertarproductoRequestBody();
            inValue.Body.producto = producto;
            return ((CapaUI.ServiceProducto.WebServiceProductoSoap)(this)).ServiceinsertarproductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProducto.ServicebuscaProdResponse CapaUI.ServiceProducto.WebServiceProductoSoap.ServicebuscaProd(CapaUI.ServiceProducto.ServicebuscaProdRequest request) {
            return base.Channel.ServicebuscaProd(request);
        }
        
        public CapaUI.ServiceProducto.Producto ServicebuscaProd(string producto) {
            CapaUI.ServiceProducto.ServicebuscaProdRequest inValue = new CapaUI.ServiceProducto.ServicebuscaProdRequest();
            inValue.Body = new CapaUI.ServiceProducto.ServicebuscaProdRequestBody();
            inValue.Body.producto = producto;
            CapaUI.ServiceProducto.ServicebuscaProdResponse retVal = ((CapaUI.ServiceProducto.WebServiceProductoSoap)(this)).ServicebuscaProd(inValue);
            return retVal.Body.ServicebuscaProdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServicebuscaProdResponse> CapaUI.ServiceProducto.WebServiceProductoSoap.ServicebuscaProdAsync(CapaUI.ServiceProducto.ServicebuscaProdRequest request) {
            return base.Channel.ServicebuscaProdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServicebuscaProdResponse> ServicebuscaProdAsync(string producto) {
            CapaUI.ServiceProducto.ServicebuscaProdRequest inValue = new CapaUI.ServiceProducto.ServicebuscaProdRequest();
            inValue.Body = new CapaUI.ServiceProducto.ServicebuscaProdRequestBody();
            inValue.Body.producto = producto;
            return ((CapaUI.ServiceProducto.WebServiceProductoSoap)(this)).ServicebuscaProdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceProducto.ServiceActualizaProductoResponse CapaUI.ServiceProducto.WebServiceProductoSoap.ServiceActualizaProducto(CapaUI.ServiceProducto.ServiceActualizaProductoRequest request) {
            return base.Channel.ServiceActualizaProducto(request);
        }
        
        public void ServiceActualizaProducto(CapaUI.ServiceProducto.Producto producto) {
            CapaUI.ServiceProducto.ServiceActualizaProductoRequest inValue = new CapaUI.ServiceProducto.ServiceActualizaProductoRequest();
            inValue.Body = new CapaUI.ServiceProducto.ServiceActualizaProductoRequestBody();
            inValue.Body.producto = producto;
            CapaUI.ServiceProducto.ServiceActualizaProductoResponse retVal = ((CapaUI.ServiceProducto.WebServiceProductoSoap)(this)).ServiceActualizaProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServiceActualizaProductoResponse> CapaUI.ServiceProducto.WebServiceProductoSoap.ServiceActualizaProductoAsync(CapaUI.ServiceProducto.ServiceActualizaProductoRequest request) {
            return base.Channel.ServiceActualizaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceProducto.ServiceActualizaProductoResponse> ServiceActualizaProductoAsync(CapaUI.ServiceProducto.Producto producto) {
            CapaUI.ServiceProducto.ServiceActualizaProductoRequest inValue = new CapaUI.ServiceProducto.ServiceActualizaProductoRequest();
            inValue.Body = new CapaUI.ServiceProducto.ServiceActualizaProductoRequestBody();
            inValue.Body.producto = producto;
            return ((CapaUI.ServiceProducto.WebServiceProductoSoap)(this)).ServiceActualizaProductoAsync(inValue);
        }
    }
}
