//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUI.ServiceVenta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Venta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdVentaField;
        
        private int IdClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdVenta {
            get {
                return this.IdVentaField;
            }
            set {
                if ((this.IdVentaField.Equals(value) != true)) {
                    this.IdVentaField = value;
                    this.RaisePropertyChanged("IdVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleVenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DetalleVenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDetalleVentaField;
        
        private int IdVentaField;
        
        private int IdStockField;
        
        private int CantidadField;
        
        private int TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDetalleVenta {
            get {
                return this.IdDetalleVentaField;
            }
            set {
                if ((this.IdDetalleVentaField.Equals(value) != true)) {
                    this.IdDetalleVentaField = value;
                    this.RaisePropertyChanged("IdDetalleVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdVenta {
            get {
                return this.IdVentaField;
            }
            set {
                if ((this.IdVentaField.Equals(value) != true)) {
                    this.IdVentaField = value;
                    this.RaisePropertyChanged("IdVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdStock {
            get {
                return this.IdStockField;
            }
            set {
                if ((this.IdStockField.Equals(value) != true)) {
                    this.IdStockField = value;
                    this.RaisePropertyChanged("IdStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVenta.WebServiceVentaSoap")]
    public interface WebServiceVentaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento venta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioCrearVenta", ReplyAction="*")]
        CapaUI.ServiceVenta.ServicioCrearVentaResponse ServicioCrearVenta(CapaUI.ServiceVenta.ServicioCrearVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioCrearVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceVenta.ServicioCrearVentaResponse> ServicioCrearVentaAsync(CapaUI.ServiceVenta.ServicioCrearVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioObtenerIdUltimaVenta", ReplyAction="*")]
        int ServicioObtenerIdUltimaVenta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioObtenerIdUltimaVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServicioObtenerIdUltimaVentaAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento detalle del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioCrearDetalleVenta", ReplyAction="*")]
        CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponse ServicioCrearDetalleVenta(CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioCrearDetalleVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponse> ServicioCrearDetalleVentaAsync(CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioCrearVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioCrearVenta", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceVenta.ServicioCrearVentaRequestBody Body;
        
        public ServicioCrearVentaRequest() {
        }
        
        public ServicioCrearVentaRequest(CapaUI.ServiceVenta.ServicioCrearVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioCrearVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceVenta.Venta venta;
        
        public ServicioCrearVentaRequestBody() {
        }
        
        public ServicioCrearVentaRequestBody(CapaUI.ServiceVenta.Venta venta) {
            this.venta = venta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioCrearVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioCrearVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceVenta.ServicioCrearVentaResponseBody Body;
        
        public ServicioCrearVentaResponse() {
        }
        
        public ServicioCrearVentaResponse(CapaUI.ServiceVenta.ServicioCrearVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioCrearVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioCrearVentaResult;
        
        public ServicioCrearVentaResponseBody() {
        }
        
        public ServicioCrearVentaResponseBody(bool ServicioCrearVentaResult) {
            this.ServicioCrearVentaResult = ServicioCrearVentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioCrearDetalleVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioCrearDetalleVenta", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequestBody Body;
        
        public ServicioCrearDetalleVentaRequest() {
        }
        
        public ServicioCrearDetalleVentaRequest(CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioCrearDetalleVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaUI.ServiceVenta.DetalleVenta detalle;
        
        public ServicioCrearDetalleVentaRequestBody() {
        }
        
        public ServicioCrearDetalleVentaRequestBody(CapaUI.ServiceVenta.DetalleVenta detalle) {
            this.detalle = detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioCrearDetalleVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioCrearDetalleVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponseBody Body;
        
        public ServicioCrearDetalleVentaResponse() {
        }
        
        public ServicioCrearDetalleVentaResponse(CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioCrearDetalleVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioCrearDetalleVentaResult;
        
        public ServicioCrearDetalleVentaResponseBody() {
        }
        
        public ServicioCrearDetalleVentaResponseBody(bool ServicioCrearDetalleVentaResult) {
            this.ServicioCrearDetalleVentaResult = ServicioCrearDetalleVentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceVentaSoapChannel : CapaUI.ServiceVenta.WebServiceVentaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceVentaSoapClient : System.ServiceModel.ClientBase<CapaUI.ServiceVenta.WebServiceVentaSoap>, CapaUI.ServiceVenta.WebServiceVentaSoap {
        
        public WebServiceVentaSoapClient() {
        }
        
        public WebServiceVentaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceVentaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVentaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVentaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceVenta.ServicioCrearVentaResponse CapaUI.ServiceVenta.WebServiceVentaSoap.ServicioCrearVenta(CapaUI.ServiceVenta.ServicioCrearVentaRequest request) {
            return base.Channel.ServicioCrearVenta(request);
        }
        
        public bool ServicioCrearVenta(CapaUI.ServiceVenta.Venta venta) {
            CapaUI.ServiceVenta.ServicioCrearVentaRequest inValue = new CapaUI.ServiceVenta.ServicioCrearVentaRequest();
            inValue.Body = new CapaUI.ServiceVenta.ServicioCrearVentaRequestBody();
            inValue.Body.venta = venta;
            CapaUI.ServiceVenta.ServicioCrearVentaResponse retVal = ((CapaUI.ServiceVenta.WebServiceVentaSoap)(this)).ServicioCrearVenta(inValue);
            return retVal.Body.ServicioCrearVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceVenta.ServicioCrearVentaResponse> CapaUI.ServiceVenta.WebServiceVentaSoap.ServicioCrearVentaAsync(CapaUI.ServiceVenta.ServicioCrearVentaRequest request) {
            return base.Channel.ServicioCrearVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceVenta.ServicioCrearVentaResponse> ServicioCrearVentaAsync(CapaUI.ServiceVenta.Venta venta) {
            CapaUI.ServiceVenta.ServicioCrearVentaRequest inValue = new CapaUI.ServiceVenta.ServicioCrearVentaRequest();
            inValue.Body = new CapaUI.ServiceVenta.ServicioCrearVentaRequestBody();
            inValue.Body.venta = venta;
            return ((CapaUI.ServiceVenta.WebServiceVentaSoap)(this)).ServicioCrearVentaAsync(inValue);
        }
        
        public int ServicioObtenerIdUltimaVenta() {
            return base.Channel.ServicioObtenerIdUltimaVenta();
        }
        
        public System.Threading.Tasks.Task<int> ServicioObtenerIdUltimaVentaAsync() {
            return base.Channel.ServicioObtenerIdUltimaVentaAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponse CapaUI.ServiceVenta.WebServiceVentaSoap.ServicioCrearDetalleVenta(CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest request) {
            return base.Channel.ServicioCrearDetalleVenta(request);
        }
        
        public bool ServicioCrearDetalleVenta(CapaUI.ServiceVenta.DetalleVenta detalle) {
            CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest inValue = new CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest();
            inValue.Body = new CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequestBody();
            inValue.Body.detalle = detalle;
            CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponse retVal = ((CapaUI.ServiceVenta.WebServiceVentaSoap)(this)).ServicioCrearDetalleVenta(inValue);
            return retVal.Body.ServicioCrearDetalleVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponse> CapaUI.ServiceVenta.WebServiceVentaSoap.ServicioCrearDetalleVentaAsync(CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest request) {
            return base.Channel.ServicioCrearDetalleVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaUI.ServiceVenta.ServicioCrearDetalleVentaResponse> ServicioCrearDetalleVentaAsync(CapaUI.ServiceVenta.DetalleVenta detalle) {
            CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest inValue = new CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequest();
            inValue.Body = new CapaUI.ServiceVenta.ServicioCrearDetalleVentaRequestBody();
            inValue.Body.detalle = detalle;
            return ((CapaUI.ServiceVenta.WebServiceVentaSoap)(this)).ServicioCrearDetalleVentaAsync(inValue);
        }
    }
}
